### PR TITLE
Julevask 2022 tasks

### PR DESCRIPTION
**Pull request by kwinkunks**
Completes most of the Julevask tasks; this PR will check if CI is running. If it is, that will only leave a few items on the Community checklist (security policy and templates).

### CODE REVIEW

**Comment by kwinkunks** [comment]
CI apparently broken. And is the GitHub action trying to use Py 3.1 because 3.10 is in the list and getting interpreted as a float? Will look at it after Xmas.

**Review by eivindjahren — APPROVED** [review]

**Comment by eivindjahren** [comment]
Look good, you need to enclose 3.10 in quotes to get ci to pass.

**Comment by kwinkunks** [comment]
@eivindjahren Turned out that Py 3.11 needed some less trivial changes. Please can you give 569184a a quick look when you get a chance? /matt

**Comment by eivindjahren** [comment]
I see we have to remove the required status for 3.7 builds and add 3.10 build as required. The Field change I am wondering a bit if there is a `pydantic.dataclasses` equivalent. Should probably not mix those.

**Comment by kwinkunks** [comment]
- Updated the status checks to include Py 3.9 and 3.10 (but not 3.11, not sure if we want to require that yet), and removed Py 3.7 requirement.
- Regarding `pydantic.Field`, the docs for `pydantic.dataclasses` say:

> fields that require a default_factory can be specified by either a `pydantic.Field` or a `dataclasses.field`.

The `Field` class is available as `pydantic.dataclasses.Field` as well, but since we already have a few uses of `dataclasses.field` in the code, I switched all my uses of `Field` to use the same.

**Pull request merged**
